baseurl = "/"
copyright = "Burhan Ahmad Mudassar"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableEmoji = true
enableGitInfo = false
footnotereturnlinkcontents = "<sup>^</sup>"
hasCJKLanguage = false
ignoreFiles = ["\\.ipynb$", "\\.Rmd$", ".ipynb_checkpoints$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
removePathAccents = true
summaryLength = 30
theme = "academic"
title = "Burhan Ahmad Mudassar"
[imaging]
anchor = "smart"
quality = 90
resampleFilter = "lanczos"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = false
[markup.tableOfContents]
endLevel = 3
startLevel = 2
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
section = ["HTML", "RSS"]
[permalinks]
authors = "/author/:slug/"
categories = "/category/:slug/"
publication_types = "/publication-type/:slug/"
tags = "/tag/:slug/"
[related]
includeNewer = true
threshold = 80
toLower = true
[[related.indices]]
name = "title"
weight = 60
[[related.indices]]
name = "summary"
weight = 50
[[related.indices]]
name = "tags"
weight = 80
[[related.indices]]
name = "categories"
weight = 70
[[related.indices]]
name = "authors"
weight = 20
[taxonomies]
author = "authors"
category = "categories"
publication_type = "publication_types"
tag = "tags"
