abstract_length = 135
address_format = "en-us"
appointment_url = ""
date_format = "Jan 2, 2006"
day_night = true
description = ""
diagram = false
directions = ""
docs_section_pager = true
email = "burhanahmadmudassar@gmail.com"
font = ""
font_size = "L"
highlight = true
highlight_languages = ["C++", "Python", "r"]
highlight_superuser = false
link_authors = true
local_business_type = ""
math = false
office_hours = []
org_name = ""
phone = ""
plugins_js = []
privacy_pack = false
reading_time = true
section_pager = false
sharing = true
sharing_image = ""
site_type = "Person"
theme = "minimal"
time_format = "3:04 PM"
twitter = ""
[address]
city = "Atlanta"
country = "United States"
country_code = "US"
postcode = "30332"
region = "GA"
street = "266 Ferst Drive NW"
[address_formats.de]
delimiters = ["<br>", " ", ""]
order = ["street", "postcode", "city"]
[address_formats.en-gb]
delimiters = [", ", ", ", ", ", ""]
order = ["street", "city", "region", "postcode"]
[address_formats.en-us]
delimiters = [", ", ", ", " ", ""]
order = ["street", "city", "region", "postcode"]
[address_formats.fr-fr]
delimiters = ["<br>", " ", ""]
order = ["street", "postcode", "city"]
[address_formats.zh]
delimiters = [" ", " ", " ", ""]
order = ["postcode", "region", "city", "street"]
[avatar]
gravatar = false
shape = "circle"
[cms]
netlify_cms = true
[comments]
engine = 0
[comments.commentable]
docs = true
page = true
post = true
project = true
publication = true
talk = true
[comments.commento]
url = ""
[comments.disqus]
shortname = ""
show_count = true
[coordinates]
latitude = ""
longitude = ""
[copyright_license]
allow_commercial = false
allow_derivatives = false
enable = false
notice = "This work is licensed under {license}"
share_alike = true
[edit_page]
content_dir = ""
repo_branch = "master"
repo_url = "https://github.com/burhanmudassar"
[edit_page.editable]
docs = true
page = false
post = false
[main_menu]
align = "l"
show_logo = true
[map]
api_key = ""
engine = 2
zoom = 15
[marketing]
google_analytics = ""
google_tag_manager = ""
[projects]
post_view = 2
publication_view = 2
talk_view = 2
[publications]
citation_style = "apa"
date_format = "January 2006"
[search]
engine = 1
[search.algolia]
api_key = ""
app_id = ""
index_name = ""
show_logo = false
[show_related]
docs = true
page = false
post = true
project = true
publication = true
talk = true
[[contact_links]]
icon = "twitter"
icon_pack = "fab"
link = "https://twitter.com/Twitter"
name = "DM Me"
[[contact_links]]
icon = "comments"
icon_pack = "fas"
link = "https://discourse.gohugo.io"
name = "Discuss on Forum"
